#!/bin/sh

### Set ARCH variables
export DEVICE=ARMv7
export TOOLCHAIN=$CWD/toolchain
export ARCH=armv7-a
export PATH=$TOOLCHAIN/bin:$PATH
export CFLAGS="-march=${ARCH} -mcpu=cortex-a9 -mfpu=vfpv3-d16 -mfloat-abi=hard"
export CHOST=arm-linux-gnueabihf
export CC=$TOOLCHAIN/bin/arm-linux-gnueabihf-gcc
export CXX=$TOOLCHAIN/bin/arm-linux-gnueabihf-g++
export AR=$TOOLCHAIN/bin/arm-linux-gnueabihf-ar
export RANLIB=$TOOLCHAIN/bin/arm-linux-gnueabihf-ranlib
export STRIP=$TOOLCHAIN/bin/arm-linux-gnueabihf-strip
export DEVICEAPPS=$CWD/code/ARMv7/Shares/Apps
export OUTPUTDIR=$CWD/output

### Download and install toolchain
if [ ! -f $CWD/toolchain/.arm-linux-gnueabihf ]; then
if [ ! -f $CWD/dl/gcc-linaro-arm-linux-gnueabihf-4.7-2013.04-20130415_linux.tar.xz ]; then
    wget -P $CWD/dl/ https://releases.linaro.org/13.04/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.7-2013.04-20130415_linux.tar.xz
fi
tar -vxf $CWD/dl/gcc-linaro-arm-linux-gnueabihf-4.7-2013.04-20130415_linux.tar.xz -C $CWD/toolchain --strip-components=1

touch $CWD/toolchain/.arm-linux-gnueabihf
fi

echo
echo $DEVICE
echo "Toolchain: $CHOST"
echo "Location: $TOOLCHAIN"
echo
